# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PostSafety' do
use_frameworks!
pod 'IQKeyboardManagerSwift', '5.0.0'
#pod 'TPKeyboardAvoidingSwift'
pod 'Alamofire', ‘4.2.0’
pod 'SwiftyJSON', '3.1.3'
pod 'Reachability'
pod 'RealmSwift'
pod 'ACProgressHUD-Swift', '~> 1.3'
pod 'DZNEmptyDataSet'

# Pods for FirebaseNotificationDemo
pod 'Firebase/Core'
pod 'Firebase/Messaging'

pod 'DGElasticPullToRefresh'

pod 'Fabric', '~> 1.7.11'
pod 'Crashlytics', '~> 3.10.7'

end
